In [32]:
import pandas as pd
import numpy as np
import importlib
import gc
import sys
import warnings
sys.path.append('./scripts')  
import preprocesamiento
import feature_engineering
import model_xgboost
import model_xgboost_keepsimple
importlib.reload(preprocesamiento)
importlib.reload(model_xgboost)
importlib.reload(model_xgboost_keepsimple)
importlib.reload(feature_engineering)
warnings.filterwarnings("ignore")

# Experimento 10: 
- XGBOOST
- Usando funcion entrenamiento: model_xgboost.semillerio_en_prediccion(train, test, version="v1")
- optuna = sqlite:///optuna_studies_v25.db
- Kaggle =

##### Levantamos el dataset con target ya calculado

In [2]:
df = pd.read_csv("./datasets/periodo_x_producto_con_target.csv", sep=',', encoding='utf-8')
df.shape

(31362, 19)

In [3]:
df[df['target'].isna()][['product_id', 'periodo', 'tn', 'target']]
# 20034 , 201905

       product_id  periodo          tn  target
34          20001   201911  1397.37231     NaN
35          20001   201912  1504.68856     NaN
70          20002   201911  1423.57739     NaN
71          20002   201912  1087.30855     NaN
106         20003   201911   948.29393     NaN
...           ...      ...         ...     ...
31344       21274   201708     0.00867     NaN
31353       21276   201911     0.03341     NaN
31354       21276   201912     0.00892     NaN
31360       21281   201707     0.00000     NaN
31361       21281   201708     0.03500     NaN

[2328 rows x 4 columns]

In [26]:
columnas_baseline = df.columns.tolist()
columnas_baseline

['product_id',
 'periodo',
 'nacimiento_producto',
 'muerte_producto',
 'mes_n',
 'total_meses',
 'producto_nuevo',
 'ciclo_de_vida_inicial',
 'cat1',
 'cat2',
 'cat3',
 'brand',
 'sku_size',
 'stock_final',
 'tn',
 'plan_precios_cuidados',
 'cust_request_qty',
 'cust_request_tn',
 'target']

##### Preprocesamiento a la minima expresión :)

In [4]:
df = feature_engineering.create_category_features_cat1(df)
df = feature_engineering.create_category_features_cat2(df)
df = feature_engineering.create_category_features_cat3(df)

##### aplicamos OHE
# df = preprocesamiento.aplicarOHE(df)
df.shape

(31362, 28)

### Feature Engineering

##### Neural Prophet

In [5]:
neural_prophet_fe = pd.read_csv("./datasets/features_neuralprophet_completo.csv", sep=',', encoding='utf-8')
neural_prophet_fe['ds'] = pd.to_datetime(neural_prophet_fe['ds'], errors='coerce')
# Versión alternativa más robusta:
neural_prophet_fe['periodo'] = neural_prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
neural_prophet_fe = neural_prophet_fe[['periodo', 'product_id', 'trend', "season_yearly", "season_monthly"]]
df = df.merge(neural_prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 31)

##### Prophet

In [6]:
prophet_fe = pd.read_csv("./datasets/prophet_features_tn_zscore.csv", sep=',', encoding='utf-8')
prophet_fe['ds'] = pd.to_datetime(prophet_fe['ds'], errors='coerce')
prophet_fe['periodo'] = prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
prophet_fe = prophet_fe[['periodo', 'product_id', 'trend_add', "yearly_add", "additive_terms", 'trend_mult', 'yearly_mult', 'multiplicative_terms']]
df = df.merge(prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 37)

##### FE Moviles

In [7]:
df = feature_engineering.get_lags(df, "tn", 201912)
df = feature_engineering.get_delta_lags(df, "tn", 24)
df = feature_engineering.get_rolling_means(df, "tn", 201912)
df = feature_engineering.get_rolling_stds(df, "tn", 201912)
df = feature_engineering.get_rolling_mins(df, "tn", 201912)
df = feature_engineering.get_rolling_maxs(df, "tn", 201912)
df = feature_engineering.get_rolling_medians(df, "tn", 201912)
df = feature_engineering.get_rolling_skewness(df, "tn", 201912)
df = feature_engineering.get_autocorrelaciones(df, "tn", 201912)
df.shape

(31362, 599)

In [8]:
df = feature_engineering.get_lags(df, "cust_request_qty", 201912)
df = feature_engineering.get_delta_lags(df, "cust_request_qty", 24)
df = feature_engineering.get_rolling_means(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_stds(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_mins(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_maxs(df, "cust_request_qty", 201912)

In [ ]:
df = feature_engineering.get_lags(df, "cust_request_qty", 201912)
df = feature_engineering.get_delta_lags(df, "cust_request_qty", 24)
df = feature_engineering.get_rolling_means(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_stds(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_mins(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_maxs(df, "cust_request_qty", 201912)
df.shape

(31362, 1500)

##### FE Diana

In [8]:
df = feature_engineering.calcular_diferencia_con_medias_moviles(df)
df = feature_engineering.calcular_ratios_con_medias_moviles(df)
df.shape

(31362, 635)

##### FE Moviles sobre otras variables

In [56]:
# #  stock final
# df = feature_engineering.get_lagsEspecificos(df, col='stock_final_zscore')
# df = feature_engineering.get_delta_lags_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_means_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_stds_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_medians_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_mins_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='stock_final_zscore')

#  cust_request_qty
# df = feature_engineering.get_lagsEspecificos(df, col='cust_request_qty')
# df = feature_engineering.get_delta_lags_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_means_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_stds_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_mins_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_medians_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='cust_request_qty')

##### FE Calendario

In [9]:
df = feature_engineering.generar_ids(df)
df = feature_engineering.get_componentesTemporales(df)
df = feature_engineering.get_anomaliasPoliticas(df)
# df = feature_engineering.descomposicion_serie_temporal(df, col='tn')
df.shape

(31362, 660)

##### FE sobre FE

In [10]:
df = feature_engineering.chatGPT_features_serie(df, "tn")
df = feature_engineering.mes_con_feriado(df)
df.shape

(31362, 689)

##### Variables Exogenas

In [11]:
df = feature_engineering.get_dolar(df)
df = feature_engineering.get_IPC(df)
df['ipc'] = df['ipc'].str.replace(',', '.').astype(float)
df['dolar'] = df['dolar'].str.replace(',', '.').astype(float)
# df.drop(columns=['ds'], inplace=True)
#df.fillna(0, inplace=True) ##### EXPERIMENTAR
df = feature_engineering.correlacion_exogenas(df)
df = feature_engineering.get_mes_receso_escolar(df)
df.shape

(31362, 692)

##### Nuevas FE

In [12]:
df = feature_engineering.create_ratio_features(df)
df = feature_engineering.enhance_lifecycle_features(df)
# df = feature_engineering.create_category_features(df)
df = feature_engineering.create_regime_features(df)
df = feature_engineering.create_nonlinear_trends(df)
df = feature_engineering.create_temporal_interactions(df)
df = feature_engineering.create_asymmetric_window_features(df)
# df = feature_engineering.recomendaciones_deepseek(df)
df = feature_engineering.get_nuevas_features(df)
df.shape

(31362, 727)

##### Ceros

In [ ]:
df = feature_engineering.agregar_ceros_consecutivos_atras(df, col_tn='tn_original')
df = feature_engineering.agregar_no_ceros_consecutivos_atras(df, col_tn='tn_original')
df = feature_engineering.agregar_ceros_ultimos_n_meses(df, ventanas=[1,2,3,4,5,6,12], col_tn='tn_original')
df = feature_engineering.agregar_min_max_ult_n(df, n_list=(1,2,3,4,5,6,12), col_tn='tn_original')
df.shape

##### Elimino aquellas que no sirven

In [13]:
importantes = pd.read_csv("./feature_importance/exp04_3.csv", sep=',', encoding='utf-8')
no_importantes = importantes[importantes['importance'] <= 100]
no_importantes = no_importantes[~no_importantes['feature'].isin(columnas_baseline)]
no_importantes

                  feature  importance
67        tn_vs_prev_year         100
68     tn_delta_lag5_lag8          99
69       tn_rolling_min_4          96
70               tn_lag_5          95
71       tn_rolling_std_6          95
..                    ...         ...
677          dia_del_year           0
678               cat2_TE           0
680            cat2_PIEL1           0
681            cat2_OTROS           0
682  tn_is_outlier_3sigma           0

[608 rows x 2 columns]

In [14]:
cols_a_eliminar = no_importantes.feature.unique()
print(f"Antes de eliminar: {df.shape[1]} columnas")
df = df.drop(columns=cols_a_eliminar, errors='ignore')
print(f"Después de eliminar: {df.shape[1]} columnas")

Antes de eliminar: 1144 columnas
Después de eliminar: 684 columnas

Eliminar object/categorical columnas

In [15]:
df = df.select_dtypes(exclude=['datetime', 'datetime64', 'object'])

Train Test Split

In [13]:
training = [
    201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708, 201709,
    201710, 201711, 201712, 201801, 201802, 201803, 201804, 201805,
    201806, 201807, 201808, 201809, 201810, 201811, 201812,
    201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908
]

validation = [
    201909
]


testing = [
    201910
]

prediction = [
    201912  
]

In [14]:
df_train = df[df['periodo'].isin(training)].copy()
df_val = df[df['periodo'].isin(validation)].copy()
df_test = df[df['periodo'].isin(testing)].copy()
df_pred = df[df['periodo'].isin(prediction)].copy()

gc.collect()

0

Entrenamiento

In [59]:
# Hay casos como este donde el producto muere en 2019006, por lo tanto tienen los dos ultimos target vacios.
# df_train[df_train['product_id']==20034][['product_id', 'periodo', 'tn', 'target']]
# 20034 , 201905

In [18]:
df_train['target'].fillna(0, inplace=True)
df_val['target'].fillna(0, inplace=True)
df_test['target'].fillna(0, inplace=True)

In [34]:
model_xgboost_keepsimple.optimizar_con_optuna_sin5FCV_con_semillerio_db(df_train=df_train, df_val=df_val, version="v26", n_trials=500)

Para visualizar los resultados en tiempo real:
1. Abre otra terminal y ejecuta:
   optuna-dashboard sqlite:///optuna_studies_v26.db
2. Abre en tu navegador: http://127.0.0.1:8080/

[I 2025-07-16 09:03:17,060] A new study created in RDB with name: xgboost_optimization_v26

⏳ Ejecutando Trial #0
[0]	validation_0-rmse:101.86148
[1]	validation_0-rmse:98.63045
[2]	validation_0-rmse:95.86212
[3]	validation_0-rmse:93.02808
[4]	validation_0-rmse:90.16587
[5]	validation_0-rmse:87.30848
[6]	validation_0-rmse:84.88291
[7]	validation_0-rmse:81.95609
[8]	validation_0-rmse:79.71684
[9]	validation_0-rmse:77.07052
[10]	validation_0-rmse:74.47437
[11]	validation_0-rmse:72.14805
[12]	validation_0-rmse:70.17291
[13]	validation_0-rmse:68.06698
[14]	validation_0-rmse:66.30857
[15]	validation_0-rmse:64.76947
[16]	validation_0-rmse:63.37569
[17]	validation_0-rmse:62.00684
[18]	validation_0-rmse:60.41785
[19]	validation_0-rmse:58.91747
[20]	validation_0-rmse:57.21977
[21]	validation_0-rmse:55.83287
[22]	validation_0-rmse:54.41938
[23]	validation_0-rmse:53.18278
[24]	validation_0-rmse:51.96990
[25]	validation_0-rmse:50.67443
[26]	validation_0-rmse:49.79511
[27]	validation_0-rmse:48.97135
[28]	validation_0-rmse:48.08121
[29]	validation_0-rmse:47.02765
[30]	validation_0-rmse:45.92861
[31]	validation_0-rmse:44.97711
[32]	validation_0-rmse:43.96392
[33]	validation_0-rmse:43.07555
[34]	validation_0-rmse:42.45721
[35]	validation_0-rmse:41.58126
[36]	validation_0-rmse:40.97226
[37]	validation_0-rmse:40.38852
[38]	validation_0-rmse:39.77275
[39]	validation_0-rmse:39.35146
[40]	validation_0-rmse:38.65216
[41]	validation_0-rmse:38.02766
[42]	validation_0-rmse:37.69442
[43]	validation_0-rmse:37.27192
[44]	validation_0-rmse:36.98513
[45]	validation_0-rmse:36.49915
[46]	validation_0-rmse:35.99905
[47]	validation_0-rmse:35.64139
[48]	validation_0-rmse:35.22282
[49]	validation_0-rmse:35.03306
[50]	validation_0-rmse:34.65927
[51]	validation_0-rmse:34.51154
[52]	validation_0-rmse:34.25606
[53]	validation_0-rmse:34.02346
[54]	validation_0-rmse:33.69269
[55]	validation_0-rmse:33.67276
[56]	validation_0-rmse:33.26443
[57]	validation_0-rmse:33.11277
[58]	validation_0-rmse:32.89409
[59]	validation_0-rmse:32.67650
[60]	validation_0-rmse:32.42367
[61]	validation_0-rmse:32.19617
[62]	validation_0-rmse:31.99838
[63]	validation_0-rmse:31.89636
[64]	validation_0-rmse:31.60085
[65]	validation_0-rmse:31.44838
[66]	validation_0-rmse:31.31431
[67]	validation_0-rmse:31.17674
[68]	validation_0-rmse:30.92670
[69]	validation_0-rmse:30.80037
[70]	validation_0-rmse:30.67707
[71]	validation_0-rmse:30.54956
[72]	validation_0-rmse:30.43323
[73]	validation_0-rmse:30.14660
[74]	validation_0-rmse:30.04600
[75]	validation_0-rmse:29.93494
[76]	validation_0-rmse:29.81494
[77]	validation_0-rmse:29.67066
[78]	validation_0-rmse:29.59848
[79]	validation_0-rmse:29.63299
[80]	validation_0-rmse:29.55763
[81]	validation_0-rmse:29.55441
[82]	validation_0-rmse:29.42994
[83]	validation_0-rmse:29.37948
[84]	validation_0-rmse:29.31780
[85]	validation_0-rmse:29.31340
[86]	validation_0-rmse:29.27917
[87]	validation_0-rmse:29.23584
[88]	validation_0-rmse:29.13267
[89]	validation_0-rmse:29.04578
[90]	validation_0-rmse:28.97221
[91]	validation_0-rmse:28.88918
[92]	validation_0-rmse:28.83742
[93]	validation_0-rmse:28.76913
[94]	validation_0-rmse:28.71579
[95]	validation_0-rmse:28.67278
[96]	validation_0-rmse:28.71330
[97]	validation_0-rmse:28.70109
[98]	validation_0-rmse:28.68569
[99]	validation_0-rmse:28.64036
[100]	validation_0-rmse:28.65185
[101]	validation_0-rmse:28.60506
[102]	validation_0-rmse:28.58865
[103]	validation_0-rmse:28.55954
[104]	validation_0-rmse:28.49489
[105]	validation_0-rmse:28.47443
[106]	validation_0-rmse:28.40106
[107]	validation_0-rmse:28.30292
[108]	validation_0-rmse:28.25066
[109]	validation_0-rmse:28.24157
[110]	validation_0-rmse:28.22350
[111]	validation_0-rmse:28.22482
[112]	validation_0-rmse:28.16881
[113]	validation_0-rmse:28.16964
[114]	validation_0-rmse:28.19014
[115]	validation_0-rmse:28.15445
[116]	validation_0-rmse:28.08421
[117]	validation_0-rmse:28.07956
[118]	validation_0-rmse:28.07313
[119]	validation_0-rmse:28.06033
[120]	validation_0-rmse:28.06330
[121]	validation_0-rmse:28.04224
[122]	validation_0-rmse:28.01962
[123]	validation_0-rmse:28.01294
[124]	validation_0-rmse:27.99066
[125]	validation_0-rmse:27.94234
[126]	validation_0-rmse:27.82811
[127]	validation_0-rmse:27.80447
[128]	validation_0-rmse:27.80384
[129]	validation_0-rmse:27.84541
[130]	validation_0-rmse:27.83286
[131]	validation_0-rmse:27.80287
[132]	validation_0-rmse:27.83419
[133]	validation_0-rmse:27.83031
[134]	validation_0-rmse:27.80571
[135]	validation_0-rmse:27.79031
[136]	validation_0-rmse:27.77768
[137]	validation_0-rmse:27.76087
[138]	validation_0-rmse:27.75693
[139]	validation_0-rmse:27.75682
[140]	validation_0-rmse:27.77683
[141]	validation_0-rmse:27.76013
[142]	validation_0-rmse:27.77811
[143]	validation_0-rmse:27.75800
[144]	validation_0-rmse:27.75349
[145]	validation_0-rmse:27.75726
[146]	validation_0-rmse:27.71630
[147]	validation_0-rmse:27.73468
[148]	validation_0-rmse:27.79533
[149]	validation_0-rmse:27.81026
[150]	validation_0-rmse:27.82163
[151]	validation_0-rmse:27.82750
[152]	validation_0-rmse:27.82897
[153]	validation_0-rmse:27.76778
[154]	validation_0-rmse:27.76811
[155]	validation_0-rmse:27.77023
[156]	validation_0-rmse:27.72202
[157]	validation_0-rmse:27.71883
[158]	validation_0-rmse:27.72812
[159]	validation_0-rmse:27.70664
[160]	validation_0-rmse:27.73313
[161]	validation_0-rmse:27.73090
[162]	validation_0-rmse:27.68122
[163]	validation_0-rmse:27.71841
[164]	validation_0-rmse:27.70133
[165]	validation_0-rmse:27.71225
[166]	validation_0-rmse:27.71697
[167]	validation_0-rmse:27.69273
[168]	validation_0-rmse:27.67739
[169]	validation_0-rmse:27.67995
[170]	validation_0-rmse:27.63877
[171]	validation_0-rmse:27.63992
[172]	validation_0-rmse:27.61594
[173]	validation_0-rmse:27.61608
[174]	validation_0-rmse:27.59302
[175]	validation_0-rmse:27.65835
[176]	validation_0-rmse:27.65806
[177]	validation_0-rmse:27.68727
[178]	validation_0-rmse:27.67388
[179]	validation_0-rmse:27.66259
[180]	validation_0-rmse:27.65931
[181]	validation_0-rmse:27.64106
[182]	validation_0-rmse:27.65152
[183]	validation_0-rmse:27.64427
[184]	validation_0-rmse:27.63307
[185]	validation_0-rmse:27.63511
[186]	validation_0-rmse:27.63927
[187]	validation_0-rmse:27.64202
[188]	validation_0-rmse:27.64143
[189]	validation_0-rmse:27.64883
[190]	validation_0-rmse:27.66412
[191]	validation_0-rmse:27.69044
[192]	validation_0-rmse:27.70080
[193]	validation_0-rmse:27.71019
[194]	validation_0-rmse:27.68386
[195]	validation_0-rmse:27.68792
[196]	validation_0-rmse:27.69414
[197]	validation_0-rmse:27.66043
[198]	validation_0-rmse:27.63954
[199]	validation_0-rmse:27.62548
[200]	validation_0-rmse:27.64712
[201]	validation_0-rmse:27.65487
[202]	validation_0-rmse:27.65194
[203]	validation_0-rmse:27.64667
[204]	validation_0-rmse:27.60852
[205]	validation_0-rmse:27.59859
[206]	validation_0-rmse:27.61376
[207]	validation_0-rmse:27.60634
[208]	validation_0-rmse:27.57859
[209]	validation_0-rmse:27.57333
[210]	validation_0-rmse:27.55961
[211]	validation_0-rmse:27.57413
[212]	validation_0-rmse:27.56216
[213]	validation_0-rmse:27.58675
[214]	validation_0-rmse:27.57639
[215]	validation_0-rmse:27.56064
[216]	validation_0-rmse:27.55953
[217]	validation_0-rmse:27.55867
[218]	validation_0-rmse:27.56162
[219]	validation_0-rmse:27.51683
[220]	validation_0-rmse:27.42486
[221]	validation_0-rmse:27.49257
[222]	validation_0-rmse:27.49509
[223]	validation_0-rmse:27.51264
[224]	validation_0-rmse:27.51960
[225]	validation_0-rmse:27.52850
[226]	validation_0-rmse:27.52084
[227]	validation_0-rmse:27.53672
[228]	validation_0-rmse:27.54406
[229]	validation_0-rmse:27.53230
[230]	validation_0-rmse:27.52201
[231]	validation_0-rmse:27.48475
[232]	validation_0-rmse:27.47473
[233]	validation_0-rmse:27.47092
[234]	validation_0-rmse:27.46282
[235]	validation_0-rmse:27.44822
[236]	validation_0-rmse:27.45728
[237]	validation_0-rmse:27.45435
[238]	validation_0-rmse:27.45325
[239]	validation_0-rmse:27.44295
[240]	validation_0-rmse:27.44552
[241]	validation_0-rmse:27.44176
[242]	validation_0-rmse:27.45679
[243]	validation_0-rmse:27.45678
[244]	validation_0-rmse:27.45344
[245]	validation_0-rmse:27.44701
[246]	validation_0-rmse:27.45464
[247]	validation_0-rmse:27.44840
[248]	validation_0-rmse:27.45467
[249]	validation_0-rmse:27.47466
[250]	validation_0-rmse:27.46491
[251]	validation_0-rmse:27.46244
[252]	validation_0-rmse:27.45461
[253]	validation_0-rmse:27.46296
[254]	validation_0-rmse:27.43909
[255]	validation_0-rmse:27.44878
[256]	validation_0-rmse:27.45366
[257]	validation_0-rmse:27.43912
[258]	validation_0-rmse:27.42544
[259]	validation_0-rmse:27.38731
[260]	validation_0-rmse:27.39935
[261]	validation_0-rmse:27.39251
[262]	validation_0-rmse:27.39128
[263]	validation_0-rmse:27.40644
[264]	validation_0-rmse:27.40331
[265]	validation_0-rmse:27.39994
[266]	validation_0-rmse:27.42391
[267]	validation_0-rmse:27.42742
[268]	validation_0-rmse:27.43360
[269]	validation_0-rmse:27.41587
[270]	validation_0-rmse:27.41208
[271]	validation_0-rmse:27.43845
[272]	validation_0-rmse:27.43596
[273]	validation_0-rmse:27.44331
[274]	validation_0-rmse:27.45526
[275]	validation_0-rmse:27.46675
[276]	validation_0-rmse:27.44483
[277]	validation_0-rmse:27.46832
[278]	validation_0-rmse:27.45208
[279]	validation_0-rmse:27.46326
[280]	validation_0-rmse:27.44186
[281]	validation_0-rmse:27.44259
[282]	validation_0-rmse:27.41829
[283]	validation_0-rmse:27.42093
[284]	validation_0-rmse:27.42690
[285]	validation_0-rmse:27.42719
[286]	validation_0-rmse:27.40300
[287]	validation_0-rmse:27.39748
[288]	validation_0-rmse:27.38276
[289]	validation_0-rmse:27.38181
[290]	validation_0-rmse:27.38955
[291]	validation_0-rmse:27.39435
[292]	validation_0-rmse:27.39128
[293]	validation_0-rmse:27.39038
[294]	validation_0-rmse:27.38657
[295]	validation_0-rmse:27.38261
[296]	validation_0-rmse:27.37184
[297]	validation_0-rmse:27.37094
[298]	validation_0-rmse:27.33218
[299]	validation_0-rmse:27.35281
[300]	validation_0-rmse:27.37949
[301]	validation_0-rmse:27.37802
[302]	validation_0-rmse:27.37465
[303]	validation_0-rmse:27.36024
[304]	validation_0-rmse:27.34870
[305]	validation_0-rmse:27.41870
[306]	validation_0-rmse:27.42077
[307]	validation_0-rmse:27.41922
[308]	validation_0-rmse:27.41656
[309]	validation_0-rmse:27.40719
[310]	validation_0-rmse:27.39937
[311]	validation_0-rmse:27.39317
[312]	validation_0-rmse:27.40638
[313]	validation_0-rmse:27.38887
[314]	validation_0-rmse:27.38877
[315]	validation_0-rmse:27.35728
[316]	validation_0-rmse:27.35517
[317]	validation_0-rmse:27.35209
[318]	validation_0-rmse:27.35470
[319]	validation_0-rmse:27.34009
[320]	validation_0-rmse:27.35087
[321]	validation_0-rmse:27.34710
[322]	validation_0-rmse:27.34481
[323]	validation_0-rmse:27.32175
[324]	validation_0-rmse:27.32308
[325]	validation_0-rmse:27.32441
[326]	validation_0-rmse:27.32947
[327]	validation_0-rmse:27.32162
[328]	validation_0-rmse:27.29924
[329]	validation_0-rmse:27.28558
[330]	validation_0-rmse:27.29716
[331]	validation_0-rmse:27.30100
[332]	validation_0-rmse:27.36736
[333]	validation_0-rmse:27.36478
[334]	validation_0-rmse:27.35307
[335]	validation_0-rmse:27.34591
[336]	validation_0-rmse:27.39529
[337]	validation_0-rmse:27.40076
[338]	validation_0-rmse:27.39840
[339]	validation_0-rmse:27.40423
[340]	validation_0-rmse:27.40215
[341]	validation_0-rmse:27.41815
[342]	validation_0-rmse:27.41602
[343]	validation_0-rmse:27.41598
[344]	validation_0-rmse:27.40314
[345]	validation_0-rmse:27.39204
[346]	validation_0-rmse:27.37898
[347]	validation_0-rmse:27.40574
[348]	validation_0-rmse:27.41241
[349]	validation_0-rmse:27.39810
[350]	validation_0-rmse:27.39660
[351]	validation_0-rmse:27.39935
[352]	validation_0-rmse:27.39454
[353]	validation_0-rmse:27.38953
[354]	validation_0-rmse:27.38851
[355]	validation_0-rmse:27.39630
[356]	validation_0-rmse:27.38770
[357]	validation_0-rmse:27.37467
[358]	validation_0-rmse:27.37622
[359]	validation_0-rmse:27.38094
[360]	validation_0-rmse:27.39263
[361]	validation_0-rmse:27.39326
[362]	validation_0-rmse:27.37382
[363]	validation_0-rmse:27.36262
[364]	validation_0-rmse:27.37543
[365]	validation_0-rmse:27.35962
[366]	validation_0-rmse:27.37039
[367]	validation_0-rmse:27.37840
[368]	validation_0-rmse:27.37473
[369]	validation_0-rmse:27.36794
[370]	validation_0-rmse:27.37675
[371]	validation_0-rmse:27.37487
[372]	validation_0-rmse:27.38500
[373]	validation_0-rmse:27.36041
[374]	validation_0-rmse:27.38222
[375]	validation_0-rmse:27.38798
[376]	validation_0-rmse:27.38894
[377]	validation_0-rmse:27.37431
[378]	validation_0-rmse:27.37233
[379]	validation_0-rmse:27.37093
[380]	validation_0-rmse:27.36958
[381]	validation_0-rmse:27.36747
[382]	validation_0-rmse:27.36531
[383]	validation_0-rmse:27.38044
[384]	validation_0-rmse:27.34597
[385]	validation_0-rmse:27.35298
[386]	validation_0-rmse:27.36158
[387]	validation_0-rmse:27.35703
[388]	validation_0-rmse:27.35592
[389]	validation_0-rmse:27.35680
[390]	validation_0-rmse:27.35968
[391]	validation_0-rmse:27.36351
[392]	validation_0-rmse:27.35937
[393]	validation_0-rmse:27.36389
[394]	validation_0-rmse:27.35256
[395]	validation_0-rmse:27.35540
[396]	validation_0-rmse:27.35628
[397]	validation_0-rmse:27.34944
[398]	validation_0-rmse:27.34463
[399]	validation_0-rmse:27.34775
[400]	validation_0-rmse:27.35038
[401]	validation_0-rmse:27.35136
[402]	validation_0-rmse:27.35578
[403]	validation_0-rmse:27.36074
[404]	validation_0-rmse:27.34989
[405]	validation_0-rmse:27.35684
[406]	validation_0-rmse:27.34514
[407]	validation_0-rmse:27.32806
[408]	validation_0-rmse:27.31804
[409]	validation_0-rmse:27.30447
[410]	validation_0-rmse:27.30703
[411]	validation_0-rmse:27.30985
[412]	validation_0-rmse:27.32163
[413]	validation_0-rmse:27.32500
[414]	validation_0-rmse:27.32265
[415]	validation_0-rmse:27.31738
[416]	validation_0-rmse:27.32714
[417]	validation_0-rmse:27.33358
[418]	validation_0-rmse:27.33592
[419]	validation_0-rmse:27.32344
[420]	validation_0-rmse:27.30901
[421]	validation_0-rmse:27.31602
[422]	validation_0-rmse:27.31648
[423]	validation_0-rmse:27.31910
[424]	validation_0-rmse:27.31587
[425]	validation_0-rmse:27.30417
[426]	validation_0-rmse:27.31868
[427]	validation_0-rmse:27.34164
[428]	validation_0-rmse:27.34216
[429]	validation_0-rmse:27.33906
[430]	validation_0-rmse:27.33866
[431]	validation_0-rmse:27.33554
[432]	validation_0-rmse:27.34055
[433]	validation_0-rmse:27.34269
[434]	validation_0-rmse:27.35506
[435]	validation_0-rmse:27.34864
[436]	validation_0-rmse:27.33148
[437]	validation_0-rmse:27.32918
[438]	validation_0-rmse:27.33396
[439]	validation_0-rmse:27.32593
[440]	validation_0-rmse:27.32652
[441]	validation_0-rmse:27.33389
[442]	validation_0-rmse:27.31897
[443]	validation_0-rmse:27.33222
[444]	validation_0-rmse:27.32787
[445]	validation_0-rmse:27.34420
[446]	validation_0-rmse:27.36701
[447]	validation_0-rmse:27.36529
[448]	validation_0-rmse:27.36608
[449]	validation_0-rmse:27.34865
[450]	validation_0-rmse:27.35655
[451]	validation_0-rmse:27.36673
[452]	validation_0-rmse:27.36862
[453]	validation_0-rmse:27.37711
[454]	validation_0-rmse:27.37882
[455]	validation_0-rmse:27.37336
[456]	validation_0-rmse:27.36598
[457]	validation_0-rmse:27.33789
[458]	validation_0-rmse:27.33259
[459]	validation_0-rmse:27.33227
[460]	validation_0-rmse:27.31545
[461]	validation_0-rmse:27.32015
[462]	validation_0-rmse:27.33279
[463]	validation_0-rmse:27.32888
[464]	validation_0-rmse:27.32813
[465]	validation_0-rmse:27.33323
[466]	validation_0-rmse:27.32510
[467]	validation_0-rmse:27.31821
[468]	validation_0-rmse:27.32312
[469]	validation_0-rmse:27.32650
[470]	validation_0-rmse:27.32444
[471]	validation_0-rmse:27.32403
[472]	validation_0-rmse:27.32464
[473]	validation_0-rmse:27.32458
[474]	validation_0-rmse:27.32993
[475]	validation_0-rmse:27.33419
[476]	validation_0-rmse:27.31588
[477]	validation_0-rmse:27.31846
[478]	validation_0-rmse:27.32612
[479]	validation_0-rmse:27.33192
[480]	validation_0-rmse:27.33899
[481]	validation_0-rmse:27.34310
[482]	validation_0-rmse:27.34403
[483]	validation_0-rmse:27.34025
[484]	validation_0-rmse:27.33958
[485]	validation_0-rmse:27.33529
[486]	validation_0-rmse:27.33187
[487]	validation_0-rmse:27.33309
[488]	validation_0-rmse:27.33058
[489]	validation_0-rmse:27.30744
[490]	validation_0-rmse:27.31094
[491]	validation_0-rmse:27.30789
[492]	validation_0-rmse:27.30601
[493]	validation_0-rmse:27.27151
[494]	validation_0-rmse:27.26643
[495]	validation_0-rmse:27.26309
[496]	validation_0-rmse:27.25957
[497]	validation_0-rmse:27.25901
[498]	validation_0-rmse:27.26255
[499]	validation_0-rmse:27.27220
[500]	validation_0-rmse:27.26608
[501]	validation_0-rmse:27.26152
[502]	validation_0-rmse:27.27197
[503]	validation_0-rmse:27.26494
[504]	validation_0-rmse:27.26835
[505]	validation_0-rmse:27.27366
[506]	validation_0-rmse:27.27754
[507]	validation_0-rmse:27.27661
[508]	validation_0-rmse:27.26373
[509]	validation_0-rmse:27.26303
[510]	validation_0-rmse:27.26284
[511]	validation_0-rmse:27.26828
[512]	validation_0-rmse:27.27021
[513]	validation_0-rmse:27.27189
[514]	validation_0-rmse:27.26893
[515]	validation_0-rmse:27.26710
[516]	validation_0-rmse:27.26820
[517]	validation_0-rmse:27.26415
[518]	validation_0-rmse:27.26167
[519]	validation_0-rmse:27.26207
[520]	validation_0-rmse:27.25652
[521]	validation_0-rmse:27.26275
[522]	validation_0-rmse:27.26714
[523]	validation_0-rmse:27.25846
[524]	validation_0-rmse:27.25690
[525]	validation_0-rmse:27.26311
[526]	validation_0-rmse:27.25854
[527]	validation_0-rmse:27.26092
[528]	validation_0-rmse:27.26112
[529]	validation_0-rmse:27.25997
[530]	validation_0-rmse:27.24600
[531]	validation_0-rmse:27.24092
[532]	validation_0-rmse:27.23926
[533]	validation_0-rmse:27.23293
[534]	validation_0-rmse:27.24065
[535]	validation_0-rmse:27.24408
[536]	validation_0-rmse:27.24777
[537]	validation_0-rmse:27.24723
[538]	validation_0-rmse:27.24624
[539]	validation_0-rmse:27.25680
[540]	validation_0-rmse:27.25445
[541]	validation_0-rmse:27.25675
[542]	validation_0-rmse:27.25041
[543]	validation_0-rmse:27.24510
[544]	validation_0-rmse:27.24161
[545]	validation_0-rmse:27.24969
[546]	validation_0-rmse:27.25378
[547]	validation_0-rmse:27.26465
[548]	validation_0-rmse:27.25728
[549]	validation_0-rmse:27.25964
[550]	validation_0-rmse:27.25135
[551]	validation_0-rmse:27.24615
[552]	validation_0-rmse:27.24161
[553]	validation_0-rmse:27.24517
[554]	validation_0-rmse:27.24449
[555]	validation_0-rmse:27.24661
[556]	validation_0-rmse:27.24383
[557]	validation_0-rmse:27.23714
[558]	validation_0-rmse:27.23834
[559]	validation_0-rmse:27.23337
[560]	validation_0-rmse:27.23282
[561]	validation_0-rmse:27.23056
[562]	validation_0-rmse:27.23287
[563]	validation_0-rmse:27.23559
[564]	validation_0-rmse:27.23412
[565]	validation_0-rmse:27.23077
[566]	validation_0-rmse:27.22854
[567]	validation_0-rmse:27.22660
[568]	validation_0-rmse:27.22706
[569]	validation_0-rmse:27.23415
[570]	validation_0-rmse:27.24234
[571]	validation_0-rmse:27.24170
[572]	validation_0-rmse:27.23632
[573]	validation_0-rmse:27.24562
[574]	validation_0-rmse:27.24074
[575]	validation_0-rmse:27.23178
[576]	validation_0-rmse:27.22201
[577]	validation_0-rmse:27.21894
[578]	validation_0-rmse:27.22427
[579]	validation_0-rmse:27.22168
[580]	validation_0-rmse:27.21795
[581]	validation_0-rmse:27.21800
[582]	validation_0-rmse:27.20956
[583]	validation_0-rmse:27.21146
[584]	validation_0-rmse:27.21985
[585]	validation_0-rmse:27.22472
[586]	validation_0-rmse:27.22129
[587]	validation_0-rmse:27.22182
[588]	validation_0-rmse:27.21131
[589]	validation_0-rmse:27.20625
[590]	validation_0-rmse:27.20666
[591]	validation_0-rmse:27.19674
[592]	validation_0-rmse:27.19793
[593]	validation_0-rmse:27.19727
[594]	validation_0-rmse:27.19123
[595]	validation_0-rmse:27.18895
[596]	validation_0-rmse:27.19018
[597]	validation_0-rmse:27.19196
[598]	validation_0-rmse:27.18634
[599]	validation_0-rmse:27.19740
[600]	validation_0-rmse:27.19627
[601]	validation_0-rmse:27.18966
[602]	validation_0-rmse:27.19152
[603]	validation_0-rmse:27.17786
[604]	validation_0-rmse:27.17325
[605]	validation_0-rmse:27.17235
[606]	validation_0-rmse:27.17480
[607]	validation_0-rmse:27.16770

[W 2025-07-16 09:06:59,095] Trial 0 failed with parameters: {'learning_rate': 0.03574712922600244, 'n_estimators': 956, 'max_depth': 8, 'min_child_weight': 6, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014, 'lambda': 3.3323645788192616e-08, 'alpha': 0.6245760287469893, 'max_bin': 348} because of the following error: XGBoostError('value -1 for Parameter verbosity exceed bound [0,3]\nverbosity: Flag to print out detailed breakdown of runtime.').
Traceback (most recent call last):
  File "c:\Users\Usuario\.conda\envs\py311lab3\Lib\site-packages\optuna\study\_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "c:\Users\Usuario\Documents\Universidad\austral\2025\Lab3\Lab3-MCD\notebooks\entregable\./scripts\model_xgboost_keepsimple.py", line 163, in objective
    model.fit(
  File "c:\Users\Usuario\.conda\envs\py311lab3\Lib\site-packages\xgboost\core.py", line 729, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "c:\Users\Usuario\.conda\envs\py311lab3\Lib\site-packages\xgboost\sklearn.py", line 1215, in fit
    with config_context(verbosity=self.verbosity):
  File "c:\Users\Usuario\.conda\envs\py311lab3\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "c:\Users\Usuario\.conda\envs\py311lab3\Lib\site-packages\xgboost\config.py", line 186, in config_context
    set_config(**old_config)
  File "c:\Users\Usuario\.conda\envs\py311lab3\Lib\site-packages\xgboost\config.py", line 108, in wrap
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Usuario\.conda\envs\py311lab3\Lib\site-packages\xgboost\config.py", line 132, in set_config
    _check_call(_LIB.XGBSetGlobalConfig(c_str(config)))
  File "c:\Users\Usuario\.conda\envs\py311lab3\Lib\site-packages\xgboost\core.py", line 310, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value -1 for Parameter verbosity exceed bound [0,3]
verbosity: Flag to print out detailed breakdown of runtime.
[W 2025-07-16 09:06:59,099] Trial 0 failed with value None.

XGBoostError: value -1 for Parameter verbosity exceed bound [0,3]
verbosity: Flag to print out detailed breakdown of runtime.

Prediccion

In [38]:
df_future = model_lgb.semillerio_en_prediccion_con_pesos(train, test, version="v1")

In [39]:
df_future

       periodo  product_id  target         pred
30476   201912       20001     0.0  1490.523819
30477   201912       20002     0.0  1176.601177
30478   201912       20003     0.0   760.653373
30479   201912       20004     0.0   713.971133
30480   201912       20005     0.0   610.816894
...        ...         ...     ...          ...
31357   201912       21265     0.0    -8.235051
31358   201912       21266     0.0    -8.913198
31359   201912       21267     0.0    -5.841841
31360   201912       21271     0.0    -1.394455
31361   201912       21276     0.0    -3.092464

[886 rows x 4 columns]

In [ ]:
productos_ok = pd.read_csv("https://storage.googleapis.com/open-courses/austral2025-af91/labo3v/product_id_apredecir201912.txt", sep="\t")
df_future = df_future[df_future['periodo'] == 201912]
df_future = df_future[df_future['product_id'].isin(productos_ok['product_id'].unique())]

       periodo  product_id  target         pred
30476   201912       20001     0.0  1490.523819
30477   201912       20002     0.0  1176.601177
30478   201912       20003     0.0   760.653373
30479   201912       20004     0.0   713.971133
30480   201912       20005     0.0   610.816894
...        ...         ...     ...          ...
31355   201912       21263     0.0    -6.386380
31357   201912       21265     0.0    -8.235051
31358   201912       21266     0.0    -8.913198
31359   201912       21267     0.0    -5.841841
31361   201912       21276     0.0    -3.092464

[780 rows x 4 columns]

In [ ]:
linear_regression = pd.read_csv("./outputs/predicciones_regresion_lineal_v2.csv", sep=',', encoding='utf-8')
df_future = df_future[['product_id', 'pred']]
df_future = df_future.merge(linear_regression, on='product_id', how='left')
df_future.loc[df_future['pred'] < 0, 'pred'] = df_future['tn']
# Definir el rango de product_ids
mask = (df_future['product_id'] >= 20001) & (df_future['product_id'] <= 20005)

# Asignar el valor de tn a pred para esos productos
df_future.loc[mask, 'pred'] = df_future.loc[mask, 'tn']
df_future

     product_id         pred           tn
0         20001  1232.764336  1232.764336
1         20002  1135.499014  1135.499014
2         20003   683.869748   683.869748
3         20004   551.448542   551.448542
4         20005   546.346434   546.346434
..          ...          ...          ...
775       21263     0.249044     0.249044
776       21265     0.072234     0.072234
777       21266     0.076151     0.076151
778       21267     0.075869     0.075869
779       21276     0.037895     0.037895

[780 rows x 3 columns]

In [45]:
df_future.drop(columns=['tn'], inplace=True)
df_future.rename(columns={'pred': 'tn'}, inplace=True)
df_future.to_csv("./outputs/predicciones_exp_07_lgb_v1.csv", index=False, sep=',')

Feature importance

In [78]:
model_lgb.feature_importance(df, models, "05")

In [79]:
importances = model_lgb.feature_importance_promedio(models, df.drop(columns=['target']))
importances.sort_values(by='importance', ascending=False, inplace=True) 
importances

                         feature  importance
16                    yearly_add    0.025628
0                     product_id    0.017944
1084           tn_seasonal_naive    0.014613
1119        naive_forecast_error    0.014388
1080                  tn_ytd_sum    0.012998
...                          ...         ...
1053  stock_final_rolling_max_18    0.000000
1052  stock_final_rolling_max_17    0.000000
1051  stock_final_rolling_max_16    0.000000
1050  stock_final_rolling_max_15    0.000000
630           stock_final_lag_14    0.000000

[1135 rows x 2 columns]